### ISSUE TITLE
dbsetup.sh fails on trusty tahr / ubuntu14

### ISSUE THREAD

**Issue by tesch1** [OpenVnmrJ/OpenVnmrJ#70]
/home/openvnmrj_1.1A/pgsql/pgsql.log says:

FATAL:  could not create lock file "/var/run/postgresql/.s.PGSQL.5432.lock": Permission denied

**Comment by tesch1** [comment]
needs a "chmod a+rw /var/run/postgresql" somewhere

**Comment by DanIverson** [comment]
This link ( http://askubuntu.com/questions/442295/postgresql-server-installation-keeps-failing-due-to-postgresql-common-error ) suggests a fix. However, since the postgresql.conf file is in /vnmr/pgsql/data and that directory is removed by dbsetup, we will need to fix dbsetup and /vnmr/bin/S99pgsql. On line 766 of dbsetup that has the call to pg_ctl, the -o option should append one more argument so it goes from
   -o "-N 10 -B 45 -i -c sort_mem=100000"
 to
   -o "-N 10 -B 45 -i -c sort_mem=100000 --unix_socket_directory=/tmp"
Could someone test this.

**Comment by DanIverson** [comment]
Probably all calls to pg_ctl that use the sort_mem option should also be appended with the unix_socket_directory option

**Comment by tesch1** [comment]
Even though the (new) chmod seems to be erroring, I dont see this
particular error anymore,
on Ubuntu 14.04.5.  The exact setup is reproducible with a virtual machine:

git clone --branch vagrant-builds git@github.com:tesch1/ovjTools.git
export OVJ_TOOLS=`pwd`/ovjTools
${OVJ_TOOLS}/bin/build_vm.sh ubuntu14 --branch development
cd ${OVJ_TOOLS}/vms/ubuntu14
VMGUI=y vagrant reload                 # this will reboot the VM in
graphical mode

(login)

xhost +
... ./load.nmr

**Comment by tesch1** [comment]
fixed, at least in 14.04.5
